### PR TITLE
Return pos in parserError from addErrAt

### PR DESCRIPTION
**Pull request by breml**
Return pos in parserError from addErrAt

### CODE REVIEW

**Comment by breml** [comment]
Checked the travis-ci output but for me it is unclear, why there are errors. All the checked methods are defined (with the correct arguments). The tests did run correctly when I ran them.

**Comment by PuerkitoBio** [comment]
Hello Lucas, yeah ignore the errors, I fixed them, it's because go 1.7 (tip) changed the way the `reflect` package works, you can't get the unexported methods of a type that way anymore.

As for the PR, I'd like to better understand the use of the pos field? The error already reports the position in an easy to parse format if e.g. you wanted an editor to mark the lines in error, is there a good use case that would benefit from having this information as integers?

**Comment by breml** [comment]
Hello Martin

As I have written in #9 I try to improve the error reporting for the user of my tools. Therefor the actual position of the parsing error would by helpful. 
In my opinion it is not very meaningful to parse the position information again, if it is already present as integers and the error type `parserError` already provides the required field.
In my opinion it is "smell" to return a `parserError` from `addErrAt` with `pos` set to its zero value, which is (in most cases) wrong.

Regards,
Lucas

**Comment by PuerkitoBio** [comment]
Oh! Haha I thought your PR added the `pos` field in the `parserError`, but I see it was already there, but never assigned to! It's clearly an oversight, yeah, I'll merge this.

**Pull request merged**
